"""
ai_core/demo_credentials.py
Honeypot-safe credential generator for Ghost Protocol.

Generates synthetic credentials that:
• Look realistic to attackers during honeypot sessions
• Never match real credential formats (no GitHub secret scanning triggers)
• Cannot be used against production systems
• Are clearly marked as demo/honeypot credentials internally

All generated credentials use the HP_DEMO_ prefix to:
1. Prevent accidental use against real services
2. Enable internal detection of credential exfiltration attempts
3. Avoid triggering Git secret scanning tools
4. Maintain clear attribution as demonstration-only data

SECURITY: These credentials are intentionally non-functional and designed
only for cyber deception scenarios. They follow OWASP honeypot best practices.
"""
from __future__ import annotations

import secrets
import hashlib
from typing import Literal

# ── Honeypot Prefix Convention ─────────────────────────────────────────────────
# All credentials generated by this module use the HP_DEMO_ prefix.
# This ensures they are identifiable as honeypot artifacts and will not
# trigger GitHub secret scanning or be mistaken for real credentials.

HONEYPOT_PREFIX = "HP_DEMO_"

# ── AWS-Style Credentials ──────────────────────────────────────────────────────


def generate_aws_access_key() -> str:
    """
    Generate a synthetic AWS access key for honeypot scenarios.
    
    Real AWS keys start with AKIA and are 20 characters.
    This generates a safe alternative that resembles AWS format.
    
    Returns:
        str: Honeypot AWS access key (e.g., HP_DEMO_AWS_ACCESS_KEY_A1B2C3D4)
    """
    random_hex = secrets.token_hex(4).upper()
    return f"{HONEYPOT_PREFIX}AWS_ACCESS_KEY_{random_hex}"


def generate_aws_secret_key() -> str:
    """
    Generate a synthetic AWS secret key for honeypot scenarios.
    
    Real AWS secrets are 40 characters of base64-like data.
    This generates a safe alternative.
    
    Returns:
        str: Honeypot AWS secret key (e.g., HP_DEMO_AWS_SECRET_9F8E7D6C5B4A)
    """
    random_hex = secrets.token_hex(6).upper()
    return f"{HONEYPOT_PREFIX}AWS_SECRET_{random_hex}"


# ── API Keys & Tokens ──────────────────────────────────────────────────────────


def generate_api_key(service: str = "API") -> str:
    """
    Generate a synthetic API key for honeypot scenarios.
    
    Args:
        service: Service name for the key (e.g., "STRIPE", "SENDGRID", "INTERNAL")
    
    Returns:
        str: Honeypot API key (e.g., HP_DEMO_STRIPE_KEY_1A2B3C4D)
    """
    random_hex = secrets.token_hex(4).upper()
    return f"{HONEYPOT_PREFIX}{service.upper()}_KEY_{random_hex}"


def generate_access_token(service: str = "ACCESS") -> str:
    """
    Generate a synthetic access token for honeypot scenarios.
    
    Args:
        service: Service name for the token (e.g., "GITHUB", "SLACK", "INTERNAL")
    
    Returns:
        str: Honeypot access token (e.g., HP_DEMO_GITHUB_TOKEN_8F7E6D5C)
    """
    random_hex = secrets.token_hex(4).upper()
    return f"{HONEYPOT_PREFIX}{service.upper()}_TOKEN_{random_hex}"


def generate_jwt_secret() -> str:
    """
    Generate a synthetic JWT secret for honeypot scenarios.
    
    Returns:
        str: Honeypot JWT secret (e.g., HP_DEMO_JWT_SECRET_A1B2C3D4E5F6)
    """
    random_hex = secrets.token_hex(6).upper()
    return f"{HONEYPOT_PREFIX}JWT_SECRET_{random_hex}"


def generate_webhook_secret() -> str:
    """
    Generate a synthetic webhook secret for honeypot scenarios.
    
    Returns:
        str: Honeypot webhook secret (e.g., HP_DEMO_WEBHOOK_SECRET_7F8E9D0C)
    """
    random_hex = secrets.token_hex(4).upper()
    return f"{HONEYPOT_PREFIX}WEBHOOK_SECRET_{random_hex}"


# ── Database Credentials ───────────────────────────────────────────────────────


def generate_db_password(db_type: str = "DATABASE") -> str:
    """
    Generate a synthetic database password for honeypot scenarios.
    
    Args:
        db_type: Database type (e.g., "MYSQL", "POSTGRES", "REDIS")
    
    Returns:
        str: Honeypot database password (e.g., HP_DEMO_MYSQL_PASSWORD_3C4D5E6F)
    """
    random_hex = secrets.token_hex(4).upper()
    return f"{HONEYPOT_PREFIX}{db_type.upper()}_PASSWORD_{random_hex}"


def generate_connection_string(db_type: Literal["mysql", "postgresql", "redis"] = "postgresql") -> str:
    """
    Generate a synthetic database connection string for honeypot scenarios.
    
    Args:
        db_type: Type of database connection string to generate
    
    Returns:
        str: Honeypot connection string with safe credentials
    """
    username = f"hp_demo_user_{secrets.token_hex(2)}"
    password = generate_db_password(db_type.upper())
    host = f"demo-db-{secrets.token_hex(2)}.internal"
    
    if db_type == "mysql":
        return f"mysql://{username}:{password}@{host}:3306/production_db"
    elif db_type == "postgresql":
        return f"postgresql://{username}:{password}@{host}:5432/production_db"
    elif db_type == "redis":
        return f"redis://:{password}@{host}:6379/0"
    else:
        return f"{db_type}://{username}:{password}@{host}/production_db"


# ── Passwords & Authentication ─────────────────────────────────────────────────


def generate_user_password(username: str = "user") -> str:
    """
    Generate a synthetic user password for honeypot scenarios.
    
    Args:
        username: Username the password is for (used for variety)
    
    Returns:
        str: Honeypot password (e.g., HP_DEMO_AdminPassword_7F8E)
    """
    random_hex = secrets.token_hex(2).upper()
    username_safe = username.replace("_", "").replace("-", "").title()
    return f"{HONEYPOT_PREFIX}{username_safe}Password_{random_hex}"


def generate_password_hash() -> str:
    """
    Generate a synthetic bcrypt-style password hash for honeypot scenarios.
    
    Real bcrypt hashes start with $2b$ and are 60 characters.
    This generates a realistic-looking but non-functional hash.
    
    Returns:
        str: Honeypot password hash (e.g., $HP_DEMO$12$A1B2C3D4E5F6...)
    """
    random_data = secrets.token_bytes(32)
    hash_suffix = hashlib.sha256(random_data).hexdigest()[:40]
    return f"$HP_DEMO$12${hash_suffix}"


# ── SSH & Certificates ─────────────────────────────────────────────────────────


def generate_ssh_private_key_placeholder() -> str:
    """
    Generate a placeholder for SSH private key that is clearly non-functional.
    
    Returns:
        str: Honeypot SSH key marker
    """
    key_id = secrets.token_hex(4).upper()
    return f"""-----BEGIN OPENSSH PRIVATE KEY-----
HP_DEMO_SSH_KEY_{key_id}_NOT_A_REAL_KEY
This is a synthetic honeypot credential for Ghost Protocol.
This key is intentionally non-functional and cannot be used for authentication.
Accessing this file triggers credential exfiltration detection.
-----END OPENSSH PRIVATE KEY-----"""


def generate_certificate_data() -> str:
    """
    Generate synthetic certificate data for honeypot scenarios.
    
    Returns:
        str: Base64-looking honeypot certificate placeholder
    """
    random_hex = secrets.token_hex(8).upper()
    return f"HP_DEMO_CERT_DATA_{random_hex}_NOT_REAL_CERTIFICATE"


# ── Kubernetes & Container Registry ────────────────────────────────────────────


def generate_kubeconfig_token() -> str:
    """
    Generate a synthetic Kubernetes service account token for honeypot scenarios.
    
    Real K8s tokens are JWTs. This generates a safe alternative.
    
    Returns:
        str: Honeypot Kubernetes token
    """
    random_hex = secrets.token_hex(16).upper()
    return f"{HONEYPOT_PREFIX}K8S_TOKEN_{random_hex}"


def generate_registry_password() -> str:
    """
    Generate a synthetic container registry password for honeypot scenarios.
    
    Returns:
        str: Honeypot registry password (e.g., HP_DEMO_REGISTRY_PASSWORD_9A8B)
    """
    random_hex = secrets.token_hex(4).upper()
    return f"{HONEYPOT_PREFIX}REGISTRY_PASSWORD_{random_hex}"


# ── Slack & Communication Services ─────────────────────────────────────────────


def generate_slack_webhook_url() -> str:
    """
    Generate a synthetic Slack webhook URL for honeypot scenarios.
    
    Real Slack webhooks follow the pattern:
    https://hooks.slack.com/services/T00000000/B00000000/XXXXXXXXXXXXXXXXXXXX
    
    This generates a safe alternative that maintains visual similarity.
    
    Returns:
        str: Honeypot Slack webhook URL
    """
    token = secrets.token_hex(10).upper()
    return f"https://demo-webhooks.internal/honeypot/{HONEYPOT_PREFIX}SLACK_{token}"


# ── Terraform & Infrastructure as Code ─────────────────────────────────────────


def generate_terraform_sensitive_value(var_name: str = "secret") -> str:
    """
    Generate synthetic Terraform sensitive values for honeypot scenarios.
    
    Args:
        var_name: Name of the Terraform variable
    
    Returns:
        str: Honeypot Terraform value
    """
    random_hex = secrets.token_hex(4).upper()
    var_safe = var_name.replace("_", "").upper()
    return f"{HONEYPOT_PREFIX}TF_{var_safe}_{random_hex}"


# ── Credential Detection Helper ────────────────────────────────────────────────


def is_honeypot_credential(credential: str) -> bool:
    """
    Check if a credential string is a Ghost Protocol honeypot credential.
    
    Args:
        credential: The credential string to check
    
    Returns:
        bool: True if the credential is a honeypot credential
    """
    return credential.startswith(HONEYPOT_PREFIX)


def extract_credential_type(credential: str) -> str | None:
    """
    Extract the credential type from a honeypot credential string.
    
    Args:
        credential: The credential string to analyze
    
    Returns:
        str | None: The credential type (e.g., "AWS_ACCESS_KEY") or None if not a honeypot credential
    """
    if not is_honeypot_credential(credential):
        return None
    
    # Remove prefix and extract type
    without_prefix = credential[len(HONEYPOT_PREFIX):]
    
    # Split by underscore and rejoin until we hit a hex pattern
    parts = without_prefix.split("_")
    
    # Find where the random hex starts (typically after the last meaningful part)
    type_parts = []
    for part in parts:
        # If part looks like hex and is 4+ chars, it's likely the random suffix
        if len(part) >= 4 and all(c in "0123456789ABCDEF" for c in part):
            break
        type_parts.append(part)
    
    return "_".join(type_parts) if type_parts else None


# ── Pre-Generated Credential Sets ──────────────────────────────────────────────


def get_aws_credential_pair() -> tuple[str, str]:
    """
    Generate a matching pair of AWS access key and secret key.
    
    Returns:
        tuple[str, str]: (access_key, secret_key)
    """
    return (generate_aws_access_key(), generate_aws_secret_key())


def get_database_credentials(db_type: str = "MYSQL") -> dict[str, str]:
    """
    Generate a complete set of database credentials.
    
    Args:
        db_type: Database type (e.g., "MYSQL", "POSTGRES")
    
    Returns:
        dict: Dictionary with username, password, and host
    """
    return {
        "username": f"hp_demo_{db_type.lower()}_user",
        "password": generate_db_password(db_type),
        "host": f"demo-{db_type.lower()}-prod.internal",
        "port": "3306" if db_type.upper() == "MYSQL" else "5432",
        "database": "production_db"
    }


# ── Credential Generation Summary ──────────────────────────────────────────────


def generate_credential_summary() -> dict[str, str]:
    """
    Generate example credentials of all types for documentation or testing.
    
    Returns:
        dict: Dictionary with examples of each credential type
    """
    return {
        "aws_access_key": generate_aws_access_key(),
        "aws_secret_key": generate_aws_secret_key(),
        "stripe_key": generate_api_key("STRIPE"),
        "sendgrid_key": generate_api_key("SENDGRID"),
        "github_token": generate_access_token("GITHUB"),
        "jwt_secret": generate_jwt_secret(),
        "mysql_password": generate_db_password("MYSQL"),
        "postgres_password": generate_db_password("POSTGRES"),
        "redis_password": generate_db_password("REDIS"),
        "admin_password": generate_user_password("admin"),
        "password_hash": generate_password_hash(),
        "k8s_token": generate_kubeconfig_token(),
        "registry_password": generate_registry_password(),
        "slack_webhook": generate_slack_webhook_url(),
        "terraform_secret": generate_terraform_sensitive_value("db_password"),
    }


# ── Convenience Wrapper Functions (Alternative API) ───────────────────────────


def generate_demo_api_key(service: str = "API") -> str:
    """
    Convenience wrapper for generate_api_key().
    Generate a synthetic API key for honeypot scenarios.
    
    Args:
        service: Service name for the key
    
    Returns:
        str: Honeypot API key
    """
    return generate_api_key(service)


def generate_demo_password(username: str = "user") -> str:
    """
    Convenience wrapper for generate_user_password().
    Generate a synthetic user password for honeypot scenarios.
    
    Args:
        username: Username the password is for
    
    Returns:
        str: Honeypot password
    """
    return generate_user_password(username)


def generate_demo_token(service: str = "ACCESS") -> str:
    """
    Convenience wrapper for generate_access_token().
    Generate a synthetic access token for honeypot scenarios.
    
    Args:
        service: Service name for the token
    
    Returns:
        str: Honeypot access token
    """
    return generate_access_token(service)


# ── Module Initialization ──────────────────────────────────────────────────────


if __name__ == "__main__":
    # Display example credentials for verification
    print("Ghost Protocol - Demo Credential Generator")
    print("=" * 60)
    print("\nExample Credentials (Safe for Honeypot Use):\n")
    
    examples = generate_credential_summary()
    for cred_type, cred_value in examples.items():
        print(f"{cred_type:20s}: {cred_value}")
    
    print("\n" + "=" * 60)
    print(f"All credentials use the '{HONEYPOT_PREFIX}' prefix.")
    print("These credentials will NOT trigger GitHub secret scanning.")
    print("They are intentionally non-functional and for deception only.")
